// ODR-WARNING: split translation unit for eTextureMap deleting destructor only.
// Emits __0oLeTextureMapdtv (eTextureMap::~eTextureMap(void), deleting variant).
//
// Same shape as src/ePortal___dtor_ePortal_void__000405C4.cpp, but the
// eTextureMap dtor body also calls PlatformFree() before chaining the
// base-object eTexture dtor. The (this != 0) guard, base-dtor chain, and
// the (arg1 & 1) deleting-tail dispatch through operator delete are all
// auto-generated by the SNC C++ ABI.

class cMemPool {
public:
    static cMemPool *GetPoolFromPtr(const void *);
};

struct DeleteRecord {
    short offset;
    short _pad;
    void (*fn)(void *, void *);
};

extern "C" void eTexture_dtor(void *, int) asm("__0oIeTexturedtv");

inline void operator delete(void *p) {
    cMemPool *pool = cMemPool::GetPoolFromPtr(p);
    char *block = ((char **)pool)[9];
    DeleteRecord *rec = (DeleteRecord *)(((char **)block)[7] + 0x30);
    __asm__ volatile("" ::: "memory");
    short off = rec->offset;
    void (*fn)(void *, void *) = rec->fn;
    fn(block + off, p);
    __asm__ volatile("" ::: "memory");
}

class eTextureMap {
public:
    void PlatformFree(void);
    ~eTextureMap();
};

#pragma control sched=1

eTextureMap::~eTextureMap() {
    *(void **)((char *)this + 4) = (void *)0x3848D8;
    PlatformFree();
    eTexture_dtor(this, 0);
}
